# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Enigma and Cipher 
name: Michael Tan <freonix>
email: tansiaolip//@//gmail.com
description: > # this means to ignore newlines until "baseurl:"
	Rambling of the a engineer in search
	of greater and something more. 
baseurl: ""  
url: "http://freonix.github.io" # the base hostname & protocol for your site
github_username: freonix 

# Build settings
markdown: kramdown
